name: Run tests via Docker  
  
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '00 18 * * *'
   
jobs:  
  tests:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  
  
    steps:
      #clone repo
      - uses: actions/checkout@v3
    
      - name: Get Test Results history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Run tests via docker-compose
        run: |
          docker compose build tests
          docker compose up tests

      - name: Create Test Results History
        uses: PavanMudigonda/allure-html-reporter-github-pages@v1.0
        if: always()
        id: allure-report
        with:
          token: ${{ secrets.CI_TOKEN }}
          WORKFLOW_ID: cu.yml
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          
      - name: Publish Allure report on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-results
